deploy with dynamic mongodb ip

diff --git a/Jenkins/Jenkinsfile b/Jenkins/Jenkinsfile
--- a/Jenkins/Jenkinsfile
+++ b/Jenkins/Jenkinsfile
@@ -77,24 +77,46 @@ pipeline {
             }
         }
 
-        stage('Deploy to App Servers') {
-            steps {
-                sh '''
-                    AWS_ACCOUNT_ID=$(aws sts get-caller-identity \
-                    --query Account \
-                    --output text)
+       stage('Deploy to App Servers') {
+    steps {
+        sh '''
+            AWS_ACCOUNT_ID=$(aws sts get-caller-identity \
+            --query Account \
+            --output text)
 
-                    ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
+            ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
 
-                    aws ssm send-command \
-                    --region ${AWS_REGION} \
-                    --targets "Key=tag:Name,Values=${APP_TAG_NAME}" \
-                    --document-name "AWS-RunShellScript" \
-                    --comment "Deploy application ${IMAGE_TAG}" \
-                    --parameters commands="aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}; docker pull ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest; docker rm -f app || true; docker run -d --name app --restart unless-stopped -p 3000:3000 ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
-                '''
-            }
-        }
+            MONGODB_PRIVATE_IP=$(aws ec2 describe-instances \
+            --region ${AWS_REGION} \
+            --filters "Name=tag:Name,Values=secure-n-tier-infra-dev-mongodb" \
+            --query "Reservations[].Instances[?State.Name=='running'].PrivateIpAddress | [0]" \
+            --output text)
+
+            echo "MongoDB Private IP: ${MONGODB_PRIVATE_IP}"
+
+            if [ -z "${MONGODB_PRIVATE_IP}" ] || [ "${MONGODB_PRIVATE_IP}" = "None" ]; then
+                echo "ERROR: MongoDB private IP not found"
+                exit 1
+            fi
+
+            MONGO_URI="mongodb://${MONGODB_PRIVATE_IP}:27017/crud"
+
+            echo "Deploying with MongoDB URI: ${MONGO_URI}"
+
+            aws ssm send-command \
+            --region ${AWS_REGION} \
+            --targets "Key=tag:Name,Values=${APP_TAG_NAME}" \
+            --document-name "AWS-RunShellScript" \
+            --comment "Deploy application ${IMAGE_TAG}" \
+            --parameters "commands=[
+              \"aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}\",
+              \"docker pull ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest\",
+              \"docker rm -f app || true\",
+              \"docker run -d --name app --restart unless-stopped -p 3000:3000 -e MONGO_URI=${MONGO_URI} ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest\"
+            ]"
+        '''
+    }
+}
     }
 
     post {
